#pragma once

#include <limits.h>
#include <float.h>

#include "tlimits.h"

#define LIMIT_IMPLEMENTATION(LIMIT_TYPE, LIMIT_MIN, LIMIT_MAX) \
	LIMIT_TYPE T_FUNCTION(limit_min, LIMIT_TYPE)(void) \
	{ \
		return LIMIT_MIN;\
	} \
	LIMIT_TYPE T_FUNCTION(limit_max, LIMIT_TYPE)(void) \
	{ \
		return LIMIT_MAX;\
	}

LIMIT_IMPLEMENTATION(char, CHAR_MIN, CHAR_MAX)
LIMIT_IMPLEMENTATION(uchar, 0u, UCHAR_MAX)

LIMIT_IMPLEMENTATION(int, INT_MIN, INT_MAX)
LIMIT_IMPLEMENTATION(uint, 0u, UINT_MAX)
LIMIT_IMPLEMENTATION(hint, SHRT_MIN, SHRT_MAX)
LIMIT_IMPLEMENTATION(uhint, 0u, USHRT_MAX)

LIMIT_IMPLEMENTATION(lint, LONG_MIN, LONG_MAX)
LIMIT_IMPLEMENTATION(ulint, 0ul, ULONG_MAX)
LIMIT_IMPLEMENTATION(llint, LLONG_MIN, LLONG_MAX)
LIMIT_IMPLEMENTATION(ullint, 0ull, ULLONG_MAX)

LIMIT_IMPLEMENTATION(float, FLT_MIN, FLT_MAX)
LIMIT_IMPLEMENTATION(double, DBL_MIN, DBL_MAX)
LIMIT_IMPLEMENTATION(ldouble, LDBL_MIN, LDBL_MAX)

LIMIT_IMPLEMENTATION(size_t, 0ul, SIZE_MAX)
LIMIT_IMPLEMENTATION(TFlag, false, true)
LIMIT_IMPLEMENTATION(_Bool, false, true)

#undef LIMIT_IMPLEMENTATION
