#pragma once

#include "../tbasic.h"

#define LIMIT_DECLARATION(LIMIT_TYPE) \
	LIMIT_TYPE T_FUNCTION(limit_min, LIMIT_TYPE)(void); \
	LIMIT_TYPE T_FUNCTION(limit_max, LIMIT_TYPE)(void);

LIMIT_DECLARATION(char)
LIMIT_DECLARATION(uchar)

LIMIT_DECLARATION(int)
LIMIT_DECLARATION(uint)
LIMIT_DECLARATION(hint)
LIMIT_DECLARATION(uhint)

LIMIT_DECLARATION(lint)
LIMIT_DECLARATION(ulint)
LIMIT_DECLARATION(llint)
LIMIT_DECLARATION(ullint)

LIMIT_DECLARATION(float)
LIMIT_DECLARATION(double)
LIMIT_DECLARATION(ldouble)

LIMIT_DECLARATION(size_t)
LIMIT_DECLARATION(TFlag)
LIMIT_DECLARATION(_Bool)

#undef LIMIT_DECLARATION
